import type { VokabelDimension, VokabelGruppe } from './types'

// ---------------------------------------------------------------------------
// Wortschatz für sicheres Sprechen auf C1–C2-Niveau.
// Anspruch: präzise, gehobene, idiomatische Ausdrücke, die gebildete
// Muttersprachler:innen verwenden — bewusst OBERHALB des A1–B2-Wortschatzes.
// Zwei Ordnungen: nach Wortart UND nach Thema. Deutsch + englische Übersetzung,
// Wortart-Gruppen zusätzlich mit Beispielsatz.
// Alles fest im Code (keine Netzwerkabhängigkeit); leicht erweiterbar.
// Hinweis: doppelte Anführungszeichen als String-Begrenzer, damit englische
// Apostrophe (one's, sb's) problemlos passen.
// ---------------------------------------------------------------------------

// === 1) Nach Wortart =======================================================

const wortartGruppen: VokabelGruppe[] = [
  {
    id: "verben",
    titel: "Verben",
    beschreibung: "Präzise, gehobene Verben, die einfache Allerweltsverben ersetzen und Nuancen setzen.",
    eintraege: [
      { de: "hervorheben", en: "to emphasize, highlight", beispiel: "Ich möchte besonders hervorheben, wie viel Mühe darin steckt." },
      { de: "relativieren", en: "to qualify, put into perspective", beispiel: "Man sollte diese Zahlen allerdings relativieren." },
      { de: "abwägen", en: "to weigh up (carefully)", beispiel: "Bevor wir entscheiden, müssen wir das Für und Wider abwägen." },
      { de: "einräumen", en: "to concede, admit", beispiel: "Ich muss einräumen, dass ich mich geirrt habe." },
      { de: "hinterfragen", en: "to critically question", beispiel: "Solche Selbstverständlichkeiten sollte man ruhig hinterfragen." },
      { de: "zugrunde liegen", en: "to underlie, be the basis of", beispiel: "Dem Konflikt liegt ein Missverständnis zugrunde." },
      { de: "sich abzeichnen", en: "to emerge, become apparent", beispiel: "Eine Lösung zeichnet sich langsam ab." },
      { de: "erörtern", en: "to discuss in detail, deliberate on", beispiel: "Wir haben die Frage ausführlich erörtert." },
      { de: "veranschaulichen", en: "to illustrate, demonstrate", beispiel: "Ein Beispiel kann das gut veranschaulichen." },
      { de: "nahelegen", en: "to suggest, imply", beispiel: "Die Indizien legen einen Zusammenhang nahe." },
      { de: "eingehen (auf)", en: "to address, go into", beispiel: "Auf diesen Einwand möchte ich näher eingehen." },
      { de: "sich niederschlagen (in)", en: "to be reflected in, manifest", beispiel: "Der Aufwand schlägt sich im Preis nieder." },
      { de: "untermauern", en: "to substantiate, back up", beispiel: "Er untermauerte seine These mit Daten." },
      { de: "schmälern", en: "to diminish, detract from", beispiel: "Das schmälert seine Verdienste keineswegs." },
      { de: "verdeutlichen", en: "to clarify, elucidate", beispiel: "Lassen Sie mich das kurz verdeutlichen." },
      { de: "entgegenwirken", en: "to counteract", beispiel: "Man muss dieser Tendenz frühzeitig entgegenwirken." },
      { de: "auslösen", en: "to trigger, provoke", beispiel: "Die Nachricht löste heftige Reaktionen aus." },
      { de: "sich zuspitzen", en: "to escalate, come to a head", beispiel: "Die Lage hat sich weiter zugespitzt." },
      { de: "bedingen", en: "to necessitate, bring about", beispiel: "Der hohe Anspruch bedingt einen hohen Aufwand." },
      { de: "anzweifeln", en: "to cast doubt on", beispiel: "Ich zweifle die Richtigkeit dieser Angaben an." },
      { de: "befürworten", en: "to advocate, be in favour of", beispiel: "Ich befürworte diesen Vorschlag ausdrücklich." },
      { de: "ergründen", en: "to fathom, get to the bottom of", beispiel: "Wir versuchen, die eigentliche Ursache zu ergründen." },
      { de: "überwiegen", en: "to predominate, outweigh", beispiel: "Unterm Strich überwiegen die Vorteile deutlich." },
      { de: "beleuchten", en: "to shed light on, scrutinize", beispiel: "Der Artikel beleuchtet das Problem von allen Seiten." },
      { de: "sich verhalten (zu)", en: "to relate (to), be the case", beispiel: "Wie verhält sich der Nutzen zu den Kosten?" },
    ],
  },
  {
    id: "nomen",
    titel: "Nomen",
    beschreibung: "Abstrakte, tragende Hauptwörter für Argumentation, Analyse und differenzierte Rede.",
    eintraege: [
      { de: "die Voraussetzung", en: "prerequisite, precondition", beispiel: "Gegenseitiges Vertrauen ist die Voraussetzung dafür." },
      { de: "der Widerspruch", en: "contradiction", beispiel: "Darin liegt ein offenkundiger Widerspruch." },
      { de: "die Nuance", en: "nuance", beispiel: "Es kommt hier auf feine Nuancen an." },
      { de: "das Ausmaß", en: "extent, scale", beispiel: "Das wahre Ausmaß zeigte sich erst später." },
      { de: "die Tragweite", en: "significance, implications", beispiel: "Die Tragweite der Entscheidung war enorm." },
      { de: "der Ansatz", en: "approach, starting point", beispiel: "Das ist ein durchaus vielversprechender Ansatz." },
      { de: "die Zwickmühle", en: "dilemma, catch-22", beispiel: "Da stecke ich in einer echten Zwickmühle." },
      { de: "der Zwiespalt", en: "inner conflict, ambivalence", beispiel: "Ich befinde mich in einem inneren Zwiespalt." },
      { de: "der Sachverhalt", en: "matter, state of affairs", beispiel: "Schildern Sie den Sachverhalt bitte genau." },
      { de: "die Erkenntnis", en: "insight, finding", beispiel: "Zu dieser Erkenntnis bin ich erst spät gekommen." },
      { de: "der Beleg", en: "piece of evidence, proof", beispiel: "Dafür fehlt bislang jeder Beleg." },
      { de: "die Grundlage", en: "basis, foundation", beispiel: "Das entbehrt jeder sachlichen Grundlage." },
      { de: "die Wechselwirkung", en: "interaction, interplay", beispiel: "Zwischen beiden besteht eine enge Wechselwirkung." },
      { de: "der Spielraum", en: "leeway, scope", beispiel: "Beim Preis haben wir kaum Spielraum." },
      { de: "die Kehrseite", en: "downside, flip side", beispiel: "Die Kehrseite der Medaille ist der Aufwand." },
      { de: "der Vorbehalt", en: "reservation, proviso", beispiel: "Ich stimme zu, wenn auch mit Vorbehalt." },
      { de: "die Zurückhaltung", en: "restraint, reticence", beispiel: "Er übte auffallende Zurückhaltung." },
      { de: "die Beliebigkeit", en: "arbitrariness, interchangeability", beispiel: "Das grenzt schon an Beliebigkeit." },
      { de: "der Grundsatz", en: "principle", beispiel: "Aus Grundsatz mache ich das nicht." },
      { de: "die Tendenz", en: "tendency, trend", beispiel: "Die Tendenz geht eindeutig nach oben." },
      { de: "das Bewusstsein", en: "awareness, consciousness", beispiel: "Das Bewusstsein dafür wächst allmählich." },
      { de: "die Herangehensweise", en: "approach, way of tackling sth", beispiel: "Deine Herangehensweise überzeugt mich." },
      { de: "der Stellenwert", en: "importance, standing", beispiel: "Bildung hat für sie einen hohen Stellenwert." },
      { de: "die Diskrepanz", en: "discrepancy", beispiel: "Es besteht eine Diskrepanz zwischen Anspruch und Wirklichkeit." },
      { de: "das Fingerspitzengefühl", en: "tact, sensitivity, finesse", beispiel: "Das erfordert viel Fingerspitzengefühl." },
    ],
  },
  {
    id: "adjektive",
    titel: "Adjektive",
    beschreibung: "Nuancierte Eigenschaftswörter, die pauschale Wertungen durch präzise ersetzen.",
    eintraege: [
      { de: "nachvollziehbar", en: "understandable, comprehensible", beispiel: "Deine Reaktion ist absolut nachvollziehbar." },
      { de: "differenziert", en: "nuanced, differentiated", beispiel: "Sie hat das sehr differenziert dargestellt." },
      { de: "ambivalent", en: "ambivalent, mixed", beispiel: "Ich stehe dem Ganzen ambivalent gegenüber." },
      { de: "stichhaltig", en: "cogent, valid (of arguments)", beispiel: "Dafür gibt es keine stichhaltigen Argumente." },
      { de: "tiefgreifend", en: "profound, far-reaching", beispiel: "Das hatte tiefgreifende Folgen." },
      { de: "unabdingbar", en: "indispensable, essential", beispiel: "Sorgfalt ist hier unabdingbar." },
      { de: "maßgeblich", en: "decisive, authoritative", beispiel: "Er war maßgeblich am Erfolg beteiligt." },
      { de: "ausschlaggebend", en: "decisive, crucial", beispiel: "Der Preis war letztlich ausschlaggebend." },
      { de: "zwiespältig", en: "conflicting, mixed", beispiel: "Ich habe da ein zwiespältiges Gefühl." },
      { de: "weitreichend", en: "far-reaching", beispiel: "Die Reform hat weitreichende Konsequenzen." },
      { de: "gravierend", en: "grave, serious", beispiel: "Das ist ein gravierender Fehler." },
      { de: "plausibel", en: "plausible", beispiel: "Die Erklärung klingt durchaus plausibel." },
      { de: "fundiert", en: "well-founded, sound", beispiel: "Sein Urteil ist fachlich fundiert." },
      { de: "einschlägig", en: "relevant, pertinent", beispiel: "Er verfügt über einschlägige Erfahrung." },
      { de: "bezeichnend", en: "telling, characteristic", beispiel: "Bezeichnend ist, dass niemand widersprach." },
      { de: "beträchtlich", en: "considerable, substantial", beispiel: "Der Aufwand war beträchtlich." },
      { de: "eklatant", en: "blatant, glaring", beispiel: "Das ist ein eklatanter Widerspruch." },
      { de: "subtil", en: "subtle", beispiel: "Der Unterschied ist eher subtil." },
      { de: "hinlänglich", en: "amply, sufficiently (known)", beispiel: "Das Problem ist hinlänglich bekannt." },
      { de: "voreilig", en: "hasty, premature", beispiel: "Zieh bitte keine voreiligen Schlüsse." },
      { de: "augenscheinlich", en: "evident, apparent", beispiel: "Er war augenscheinlich überfordert." },
      { de: "gewichtig", en: "weighty, significant", beispiel: "Dafür gibt es gewichtige Gründe." },
      { de: "unumstritten", en: "undisputed", beispiel: "Ihre Kompetenz ist unumstritten." },
      { de: "facettenreich", en: "multifaceted", beispiel: "Das Thema ist ausgesprochen facettenreich." },
      { de: "tragfähig", en: "viable, sustainable", beispiel: "Wir brauchen eine tragfähige Lösung." },
    ],
  },
  {
    id: "konnektoren",
    titel: "Konnektoren",
    beschreibung: "Feine Verbindungswörter, die Gedanken präzise verknüpfen und die Rede gebildet wirken lassen.",
    eintraege: [
      { de: "gleichwohl", en: "nevertheless, even so", beispiel: "Es war riskant; gleichwohl hat es sich gelohnt." },
      { de: "nichtsdestotrotz", en: "nonetheless", beispiel: "Es regnete; nichtsdestotrotz kamen viele." },
      { de: "insofern", en: "in that respect, to that extent", beispiel: "Insofern hast du völlig recht." },
      { de: "zumal", en: "especially since, all the more as", beispiel: "Wir sollten zusagen, zumal sich das selten bietet." },
      { de: "ungeachtet dessen", en: "notwithstanding that, regardless", beispiel: "Ungeachtet dessen halten wir am Plan fest." },
      { de: "mithin", en: "hence, therefore (formal)", beispiel: "Die Frist ist verstrichen; er ist mithin im Verzug." },
      { de: "demzufolge", en: "accordingly, consequently", beispiel: "Die Zahlen steigen; demzufolge läuft es gut." },
      { de: "folglich", en: "consequently, therefore", beispiel: "Die Nachfrage sank; folglich mussten wir umplanen." },
      { de: "hingegen", en: "whereas, by contrast", beispiel: "Ich mag Tee; Kaffee hingegen trinke ich selten." },
      { de: "indes", en: "however, meanwhile (formal)", beispiel: "Er versprach viel; gehalten hat er indes wenig." },
      { de: "wenngleich", en: "although, even though", beispiel: "Der Plan ist gut, wenngleich teuer." },
      { de: "obgleich", en: "although", beispiel: "Sie kam, obgleich sie müde war." },
      { de: "insoweit", en: "insofar as", beispiel: "Insoweit die Frist es zulässt, helfen wir." },
      { de: "desgleichen", en: "likewise", beispiel: "Die Kosten steigen, desgleichen der Aufwand." },
      { de: "gleichermaßen", en: "equally, alike", beispiel: "Das betrifft uns alle gleichermaßen." },
      { de: "andernfalls", en: "otherwise, failing which", beispiel: "Wir müssen uns beeilen, andernfalls verpassen wir den Zug." },
      { de: "wohingegen", en: "whereas", beispiel: "Er ist vorsichtig, wohingegen sie das Risiko sucht." },
      { de: "nämlich", en: "namely, you see (that is because)", beispiel: "Ich kann nicht kommen; ich bin nämlich verreist." },
      { de: "zumindest", en: "at least", beispiel: "Er hat sich zumindest entschuldigt." },
      { de: "geschweige denn", en: "let alone", beispiel: "Er grüßt kaum, geschweige denn, dass er hilft." },
      { de: "sofern", en: "provided that, if", beispiel: "Sofern nichts dazwischenkommt, sehen wir uns morgen." },
      { de: "dementsprechend", en: "correspondingly, accordingly", beispiel: "Die Aufgabe war schwer, dementsprechend lange dauerte sie." },
      { de: "überdies", en: "moreover, furthermore", beispiel: "Der Plan ist teuer, überdies riskant." },
      { de: "letztlich", en: "ultimately, in the end", beispiel: "Letztlich kommt es auf die Umsetzung an." },
      { de: "gleichsam", en: "as it were, so to speak", beispiel: "Er ist gleichsam das Gewissen des Teams." },
    ],
  },
  {
    id: "redewendungen",
    titel: "Redewendungen",
    beschreibung: "Idiomatische Wendungen, die Rede lebendig und muttersprachlich klingen lassen — treffsicher einsetzen.",
    eintraege: [
      { de: "etwas auf den Punkt bringen", en: "to sum sth up precisely", beispiel: "Damit hast du es auf den Punkt gebracht." },
      { de: "ins Gewicht fallen", en: "to carry weight, matter", beispiel: "Dieser Faktor fällt kaum ins Gewicht." },
      { de: "eine Rolle spielen", en: "to play a role, matter", beispiel: "Der Preis spielt dabei keine Rolle." },
      { de: "den Rahmen sprengen", en: "to go beyond the scope", beispiel: "Das würde hier den Rahmen sprengen." },
      { de: "den Nagel auf den Kopf treffen", en: "to hit the nail on the head", beispiel: "Mit der Bemerkung hast du den Nagel auf den Kopf getroffen." },
      { de: "Hand in Hand gehen", en: "to go hand in hand", beispiel: "Qualität und Aufwand gehen Hand in Hand." },
      { de: "auf der Hand liegen", en: "to be obvious", beispiel: "Die Lösung liegt eigentlich auf der Hand." },
      { de: "ins Auge fallen", en: "to catch the eye, be striking", beispiel: "Sofort ins Auge fällt die klare Struktur." },
      { de: "zu Buche schlagen", en: "to make a significant dent, count", beispiel: "Die Reparatur schlägt kräftig zu Buche." },
      { de: "in Frage stellen", en: "to call into question", beispiel: "Niemand stellt deine Kompetenz in Frage." },
      { de: "außer Frage stehen", en: "to be beyond question", beispiel: "Dass wir helfen, steht außer Frage." },
      { de: "auf der Kippe stehen", en: "to hang in the balance", beispiel: "Das Projekt steht gerade auf der Kippe." },
      { de: "den Ton angeben", en: "to set the tone, call the shots", beispiel: "In der Branche gibt sie den Ton an." },
      { de: "zur Sprache kommen", en: "to come up (in conversation)", beispiel: "Das Thema kam gestern zur Sprache." },
      { de: "ins Leere laufen", en: "to come to nothing, fall flat", beispiel: "Seine Kritik lief ins Leere." },
      { de: "Früchte tragen", en: "to bear fruit", beispiel: "Die Mühe hat endlich Früchte getragen." },
      { de: "auf tönernen Füßen stehen", en: "to stand on shaky ground", beispiel: "Diese Theorie steht auf tönernen Füßen." },
      { de: "den Kern treffen", en: "to get to the heart of it", beispiel: "Deine Frage trifft den Kern der Sache." },
      { de: "Öl ins Feuer gießen", en: "to add fuel to the fire", beispiel: "Mit dieser Bemerkung goss er nur Öl ins Feuer." },
      { de: "mit zweierlei Maß messen", en: "to apply double standards", beispiel: "Hier wird mit zweierlei Maß gemessen." },
      { de: "das Ruder herumreißen", en: "to turn things around", beispiel: "In letzter Minute rissen sie das Ruder herum." },
      { de: "jemandem den Wind aus den Segeln nehmen", en: "to take the wind out of sb's sails", beispiel: "Mit dem Zugeständnis nahm sie ihm den Wind aus den Segeln." },
      { de: "sich in Grenzen halten", en: "to be limited, stay within bounds", beispiel: "Meine Begeisterung hält sich in Grenzen." },
      { de: "auf lange Sicht", en: "in the long run", beispiel: "Auf lange Sicht zahlt sich das aus." },
      { de: "das A und O sein", en: "to be the be-all and end-all", beispiel: "Gute Vorbereitung ist das A und O." },
    ],
  },
]

// === 2) Nach Thema =========================================================

const themaGruppen: VokabelGruppe[] = [
  {
    id: "meinung",
    titel: "Meinung äußern",
    beschreibung: "Gehobene Wendungen, um differenziert Position zu beziehen und zu urteilen.",
    eintraege: [
      { de: "Ich vertrete den Standpunkt, dass …", en: "I hold the view that …" },
      { de: "Meines Erachtens …", en: "In my judgment / to my mind …" },
      { de: "Ich bin geneigt zu glauben, dass …", en: "I'm inclined to think that …" },
      { de: "Wenn ich mir ein Urteil erlauben darf, …", en: "If I may venture an opinion, …" },
      { de: "Es liegt auf der Hand, dass …", en: "It's self-evident that …" },
      { de: "Ich halte es für unabdingbar, dass …", en: "I consider it essential that …" },
      { de: "Aus meiner Sicht spricht vieles dafür, dass …", en: "From where I stand, much suggests that …" },
      { de: "Ich neige zu der Auffassung, dass …", en: "I lean towards the view that …" },
      { de: "Man kann nicht von der Hand weisen, dass …", en: "One cannot dismiss the fact that …" },
      { de: "Ich bin fest davon überzeugt, dass …", en: "I'm firmly convinced that …" },
      { de: "Es steht für mich außer Frage, dass …", en: "For me it's beyond question that …" },
      { de: "Nach reiflicher Überlegung …", en: "After careful consideration …" },
      { de: "Ich möchte zu bedenken geben, dass …", en: "I'd like to point out / raise that …" },
      { de: "Meiner Einschätzung nach …", en: "In my assessment …" },
      { de: "Ich stehe dem eher skeptisch gegenüber.", en: "I'm rather skeptical about it." },
      { de: "Ich lege Wert auf die Feststellung, dass …", en: "I want to make a point of stating that …" },
      { de: "Da scheiden sich die Geister.", en: "Opinions are divided on that." },
      { de: "Ich maße mir kein Urteil an.", en: "I won't presume to judge." },
      { de: "Grundsätzlich bin ich der Meinung, dass …", en: "In principle I'm of the opinion that …" },
      { de: "Es lässt sich nicht leugnen, dass …", en: "It can't be denied that …" },
      { de: "Ich sehe mich in meiner Ansicht bestätigt.", en: "I feel vindicated in my view." },
      { de: "Ich würde das mit Vorbehalt betrachten.", en: "I'd view that with reservations." },
      { de: "Das deckt sich mit meiner Erfahrung.", en: "That tallies with my experience." },
      { de: "Ich teile diese Auffassung nur bedingt.", en: "I only partly share that view." },
      { de: "Da bin ich anderer Auffassung.", en: "I take a different view on that." },
    ],
  },
  {
    id: "diskussion",
    titel: "Diskussion",
    beschreibung: "Redemittel, um zu argumentieren, einzuwenden und eine Debatte souverän zu steuern.",
    eintraege: [
      { de: "Dem ist entgegenzuhalten, dass …", en: "Against that it must be said that …" },
      { de: "Das greift zu kurz.", en: "That falls short / is too simplistic." },
      { de: "Das lässt sich nicht verallgemeinern.", en: "That can't be generalized." },
      { de: "Sie sprechen einen wunden Punkt an.", en: "You're touching on a sore point." },
      { de: "Um es auf den Punkt zu bringen: …", en: "To put it in a nutshell: …" },
      { de: "Da muss ich entschieden widersprechen.", en: "I must firmly disagree." },
      { de: "Im Kern geht es darum, dass …", en: "At its core, it's about …" },
      { de: "Lassen Sie mich das präzisieren.", en: "Let me be more precise." },
      { de: "Das ist ein zweischneidiges Schwert.", en: "That's a double-edged sword." },
      { de: "Das würde ich so nicht stehen lassen.", en: "I wouldn't let that stand." },
      { de: "Damit rennen Sie bei mir offene Türen ein.", en: "You're preaching to the converted." },
      { de: "Wir sollten die Kirche im Dorf lassen.", en: "Let's keep a sense of proportion." },
      { de: "Das führt uns vom Thema ab.", en: "That's taking us off topic." },
      { de: "Ich pflichte Ihnen bei.", en: "I concur with you." },
      { de: "Bei allem Respekt, …", en: "With all due respect, …" },
      { de: "Das eine schließt das andere nicht aus.", en: "The two aren't mutually exclusive." },
      { de: "Ich möchte an Ihren Punkt anknüpfen.", en: "I'd like to pick up on your point." },
      { de: "Wir reden aneinander vorbei.", en: "We're talking at cross purposes." },
      { de: "Kommen wir zum Kern der Sache.", en: "Let's get to the heart of the matter." },
      { de: "Das ist Auslegungssache.", en: "That's a matter of interpretation." },
      { de: "Ich stelle das mal zur Diskussion.", en: "Let me put that up for discussion." },
      { de: "Das relativiert die Sache erheblich.", en: "That puts things in quite a different light." },
      { de: "Wir sollten das nicht überstrapazieren.", en: "We shouldn't overstate / overwork that." },
      { de: "Fassen wir zusammen: …", en: "To summarize: …" },
      { de: "Genau darin liegt der Knackpunkt.", en: "That's exactly where the crux lies." },
    ],
  },
  {
    id: "alltag",
    titel: "Alltag",
    beschreibung: "Idiomatische Alltagswendungen, die weit über das Schulbuch hinausgehen und native klingen.",
    eintraege: [
      { de: "etwas in Kauf nehmen", en: "to put up with, accept (a downside)" },
      { de: "sich in Grenzen halten", en: "to be limited (e.g. enthusiasm)" },
      { de: "jemandem über den Weg laufen", en: "to run into someone" },
      { de: "auf die Schnelle", en: "quickly, on the fly" },
      { de: "sich (Dat.) etwas verkneifen", en: "to refrain from, bite back sth" },
      { de: "jemandem etwas hoch anrechnen", en: "to give sb great credit for sth" },
      { de: "etwas über sich ergehen lassen", en: "to endure, put up with sth" },
      { de: "aus dem Ruder laufen", en: "to get out of hand" },
      { de: "sich zusammenreißen", en: "to pull oneself together" },
      { de: "den inneren Schweinehund überwinden", en: "to overcome one's inner slacker" },
      { de: "etwas auf die lange Bank schieben", en: "to keep putting sth off" },
      { de: "jemandem geht etwas gegen den Strich", en: "sth rubs sb the wrong way" },
      { de: "sich (Dat.) etwas von der Seele reden", en: "to get sth off one's chest" },
      { de: "jemandem unter die Arme greifen", en: "to lend sb a hand" },
      { de: "sich (Dat.) den Kopf zerbrechen", en: "to rack one's brains" },
      { de: "das Handtuch werfen", en: "to throw in the towel" },
      { de: "sich (Dat.) etwas zu Herzen nehmen", en: "to take sth to heart" },
      { de: "auf Anhieb", en: "straight away, at the first attempt" },
      { de: "in trockenen Tüchern sein", en: "to be in the bag, all settled" },
      { de: "jemandem auf den Keks gehen", en: "to get on sb's nerves" },
      { de: "sich aus dem Staub machen", en: "to make oneself scarce, slip away" },
      { de: "etwas an den Nagel hängen", en: "to give sth up (a job, hobby)" },
      { de: "jemandem reinen Wein einschenken", en: "to level with sb, tell the plain truth" },
      { de: "mit Ach und Krach", en: "by the skin of one's teeth" },
      { de: "aus der Not eine Tugend machen", en: "to make a virtue of necessity" },
    ],
  },
  {
    id: "beruf",
    titel: "Beruf",
    beschreibung: "Präzise Wendungen für Arbeit, Zusammenarbeit und professionelle Kommunikation.",
    eintraege: [
      { de: "sich einarbeiten", en: "to get up to speed, settle into a role" },
      { de: "den Überblick behalten", en: "to keep track of things" },
      { de: "Prioritäten setzen", en: "to set priorities" },
      { de: "etwas in Angriff nehmen", en: "to tackle something" },
      { de: "sich abstimmen (mit)", en: "to coordinate (with)" },
      { de: "Verantwortung übernehmen", en: "to take responsibility" },
      { de: "Rücksprache halten", en: "to consult, check back" },
      { de: "zielführend arbeiten", en: "to work effectively / purposefully" },
      { de: "eine Entscheidung herbeiführen", en: "to bring about a decision" },
      { de: "etwas auf den Weg bringen", en: "to get sth underway, set sth in motion" },
      { de: "die Weichen stellen", en: "to set the course, pave the way" },
      { de: "sich vertraut machen (mit)", en: "to familiarize oneself with" },
      { de: "Handlungsbedarf sehen", en: "to see a need for action" },
      { de: "den Rahmen abstecken", en: "to define the scope" },
      { de: "Kompetenzen bündeln", en: "to pool skills / resources" },
      { de: "einen Kompromiss aushandeln", en: "to negotiate a compromise" },
      { de: "sich profilieren", en: "to distinguish oneself, make one's mark" },
      { de: "Aufgaben delegieren", en: "to delegate tasks" },
      { de: "die Erwartungen managen", en: "to manage expectations" },
      { de: "auf Augenhöhe agieren", en: "to deal with sb as equals" },
      { de: "eine Frist wahren", en: "to meet / observe a deadline" },
      { de: "sich einen Namen machen", en: "to make a name for oneself" },
      { de: "über den Tellerrand hinausschauen", en: "to think outside the box" },
      { de: "etwas ins Rollen bringen", en: "to get sth rolling" },
      { de: "eine tragfähige Lösung finden", en: "to find a viable solution" },
    ],
  },
  {
    id: "smalltalk",
    titel: "Small Talk",
    beschreibung: "Natürliche, gewandte Floskeln für lockere Gespräche jenseits der Standardfragen.",
    eintraege: [
      { de: "Wie geht's, wie steht's?", en: "How's things? (casual)" },
      { de: "Was verschafft mir die Ehre?", en: "To what do I owe the pleasure?" },
      { de: "Man sieht sich ja kaum noch!", en: "We hardly see each other anymore!" },
      { de: "Du siehst gut erholt aus.", en: "You look well-rested." },
      { de: "Wie die Zeit vergeht!", en: "How time flies!" },
      { de: "Lass uns in Kontakt bleiben.", en: "Let's stay in touch." },
      { de: "Es hat sich einiges getan.", en: "Quite a lot has happened / changed." },
      { de: "Was treibst du so?", en: "What are you up to these days?" },
      { de: "Damit hätte ich nicht gerechnet!", en: "I wouldn't have expected that!" },
      { de: "Wie man so hört, …", en: "As one hears, …" },
      { de: "Das müssen wir unbedingt mal nachholen.", en: "We really must catch up on that sometime." },
      { de: "Nicht der Rede wert.", en: "Not worth mentioning." },
      { de: "Da kann man nicht meckern.", en: "Can't complain." },
      { de: "Es läuft, wie es läuft.", en: "It is what it is." },
      { de: "Lange Rede, kurzer Sinn: …", en: "To cut a long story short: …" },
      { de: "Das musst du mir bei Gelegenheit erzählen.", en: "You must tell me about that sometime." },
      { de: "Ganz meinerseits!", en: "Likewise! / The pleasure's mine!" },
      { de: "Was macht die Kunst?", en: "How's everything going? (idiom)" },
      { de: "Man munkelt, …", en: "Rumour has it, …" },
      { de: "Da fällt mir gerade ein …", en: "That reminds me …" },
      { de: "Wollen wir uns nicht mal wiedersehen?", en: "Shouldn't we meet up again sometime?" },
      { de: "Es war mir ein Vergnügen.", en: "It's been a pleasure." },
      { de: "Bleib, wie du bist.", en: "Stay just the way you are." },
      { de: "Grüß deine Familie von mir.", en: "Give my regards to your family." },
      { de: "Wir hören voneinander.", en: "We'll be in touch." },
    ],
  },
  {
    id: "konflikte",
    titel: "Konflikte",
    beschreibung: "Wendungen, um Spannungen anzusprechen, zu deeskalieren und Streit fair zu klären.",
    eintraege: [
      { de: "Lassen Sie uns sachlich bleiben.", en: "Let's keep this objective." },
      { de: "Ich kann Ihren Unmut nachvollziehen.", en: "I can understand your displeasure." },
      { de: "Das war nicht meine Absicht.", en: "That wasn't my intention." },
      { de: "Wir sollten die Wogen glätten.", en: "We should smooth things over." },
      { de: "Reden wir Klartext.", en: "Let's talk plainly / straight." },
      { de: "Das führt zu nichts.", en: "This is getting us nowhere." },
      { de: "Ich möchte einen Schlussstrich ziehen.", en: "I'd like to draw a line under it." },
      { de: "Da gehen unsere Meinungen auseinander.", en: "That's where our opinions diverge." },
      { de: "Ich fühle mich übergangen.", en: "I feel overlooked / passed over." },
      { de: "Lassen Sie mich bitte ausreden.", en: "Please let me finish." },
      { de: "Das nehme ich Ihnen übel.", en: "I hold that against you." },
      { de: "Kommen wir auf eine sachliche Ebene zurück.", en: "Let's get back to a factual level." },
      { de: "Ich will keinen Streit vom Zaun brechen.", en: "I don't want to pick a fight." },
      { de: "Wir sollten das aus der Welt schaffen.", en: "We should clear this up for good." },
      { de: "Das ist ein Schlag ins Gesicht.", en: "That's a slap in the face." },
      { de: "Ich lenke ein.", en: "I'll give in / relent." },
      { de: "Machen wir uns nichts vor.", en: "Let's not kid ourselves." },
      { de: "Das geht mir zu weit.", en: "That's going too far for me." },
      { de: "Ich möchte mich für den Ton entschuldigen.", en: "I'd like to apologize for my tone." },
      { de: "Lassen Sie uns einen Gang zurückschalten.", en: "Let's take it down a notch." },
      { de: "Ich will Ihnen nicht zu nahe treten.", en: "I don't mean to offend you." },
      { de: "Wir müssen das im Guten klären.", en: "We need to settle this amicably." },
      { de: "Wir zerren uns nur gegenseitig runter.", en: "We're just dragging each other down." },
      { de: "Können wir uns in der Mitte treffen?", en: "Can we meet in the middle?" },
      { de: "Schwamm drüber.", en: "Let bygones be bygones. / Forget it." },
    ],
  },
]

export const dimensionen: VokabelDimension[] = [
  { id: "wortart", label: "Nach Wortart", gruppen: wortartGruppen },
  { id: "thema", label: "Nach Thema", gruppen: themaGruppen },
]

// Gesamtzahl der Einträge je Dimension (für die Anzeige).
export const anzahlNachWortart = wortartGruppen.reduce((s, g) => s + g.eintraege.length, 0)
export const anzahlNachThema = themaGruppen.reduce((s, g) => s + g.eintraege.length, 0)
