import type { VokabelGruppe } from './types'

// ---------------------------------------------------------------------------
// Wortschatz für sicheres Sprechen auf C1–C2-Niveau.
// Nach Wortarten und Redeanlässen gruppiert, damit man gezielt lernen kann.
// Alles fest im Code, keine Netzwerkabhängigkeit. Leicht erweiterbar:
// neue Gruppe oder neuen Eintrag { wort, bedeutung, beispiel } ergänzen.
// ---------------------------------------------------------------------------

export const vokabular: VokabelGruppe[] = [
  {
    id: 'verben',
    titel: 'Nützliche Verben',
    beschreibung: 'Ausdrucksstarke Verben, die deine Rede präziser und erwachsener klingen lassen.',
    eintraege: [
      { wort: 'abwägen', bedeutung: 'Vor- und Nachteile sorgfältig vergleichen, bevor man entscheidet.', beispiel: 'Ich muss die Argumente noch einmal gegeneinander abwägen.' },
      { wort: 'hinterfragen', bedeutung: 'Etwas nicht einfach hinnehmen, sondern kritisch prüfen.', beispiel: 'Man sollte solche Behauptungen ruhig hinterfragen.' },
      { wort: 'nachvollziehen', bedeutung: 'Verstehen, warum jemand so denkt oder handelt.', beispiel: 'Deine Entscheidung kann ich gut nachvollziehen.' },
      { wort: 'einschätzen', bedeutung: 'Ungefähr beurteilen, wie etwas ist oder ausgeht.', beispiel: 'Es ist schwer einzuschätzen, wie lange das dauert.' },
      { wort: 'sich auseinandersetzen mit', bedeutung: 'Sich gründlich mit einem Thema beschäftigen.', beispiel: 'Ich habe mich intensiv mit dem Thema auseinandergesetzt.' },
      { wort: 'verdeutlichen', bedeutung: 'Etwas klarer und verständlicher machen.', beispiel: 'Lass mich das an einem Beispiel verdeutlichen.' },
      { wort: 'relativieren', bedeutung: 'Etwas weniger absolut darstellen, einschränken.', beispiel: 'Ich möchte meine Aussage etwas relativieren.' },
      { wort: 'betonen', bedeutung: 'Besonders hervorheben, wie wichtig etwas ist.', beispiel: 'Ich möchte betonen, dass das nur meine Meinung ist.' },
      { wort: 'bewältigen', bedeutung: 'Eine schwierige Aufgabe erfolgreich schaffen.', beispiel: 'Diese Menge an Arbeit ist kaum zu bewältigen.' },
      { wort: 'sich beziehen auf', bedeutung: 'An etwas anknüpfen, sich auf etwas berufen.', beispiel: 'Ich beziehe mich auf das, was du vorhin gesagt hast.' },
      { wort: 'in Frage stellen', bedeutung: 'Bezweifeln, ob etwas richtig oder sinnvoll ist.', beispiel: 'Niemand stellt deine Kompetenz in Frage.' },
      { wort: 'nachgehen', bedeutung: 'Einer Sache genauer auf den Grund gehen.', beispiel: 'Dieser Frage sollten wir unbedingt nachgehen.' },
      { wort: 'aufgreifen', bedeutung: 'Ein Thema oder eine Idee aufnehmen und weiterführen.', beispiel: 'Ich würde gern deinen Punkt von eben aufgreifen.' },
      { wort: 'sich durchsetzen', bedeutung: 'Seine Meinung oder sich selbst gegen Widerstand behaupten.', beispiel: 'Mit dieser Idee wird er sich kaum durchsetzen.' },
      { wort: 'ins Auge fassen', bedeutung: 'Etwas als Möglichkeit ernsthaft in Betracht ziehen.', beispiel: 'Wir fassen einen Umzug ins Auge.' },
    ],
  },
  {
    id: 'adjektive',
    titel: 'Treffende Adjektive',
    beschreibung: 'Nuancierte Eigenschaftswörter, um Dinge differenziert zu bewerten statt nur „gut“ oder „schlecht“.',
    eintraege: [
      { wort: 'nachvollziehbar', bedeutung: 'So, dass man es gut verstehen kann.', beispiel: 'Deine Reaktion ist absolut nachvollziehbar.' },
      { wort: 'plausibel', bedeutung: 'Glaubwürdig, einleuchtend.', beispiel: 'Das klingt für mich durchaus plausibel.' },
      { wort: 'fraglich', bedeutung: 'Unsicher, zweifelhaft.', beispiel: 'Ob das funktioniert, ist noch fraglich.' },
      { wort: 'ausschlaggebend', bedeutung: 'Entscheidend, den Ausschlag gebend.', beispiel: 'Der Preis war letztlich ausschlaggebend.' },
      { wort: 'gravierend', bedeutung: 'Sehr schwerwiegend, ernst.', beispiel: 'Das ist ein gravierender Fehler.' },
      { wort: 'ambivalent', bedeutung: 'Zwiespältig, mit gemischten Gefühlen.', beispiel: 'Ich stehe dem Vorschlag ambivalent gegenüber.' },
      { wort: 'unabdingbar', bedeutung: 'Absolut notwendig, unverzichtbar.', beispiel: 'Vertrauen ist für ein Team unabdingbar.' },
      { wort: 'subtil', bedeutung: 'Fein, unauffällig, mit Feingefühl.', beispiel: 'Der Unterschied ist eher subtil.' },
      { wort: 'einleuchtend', bedeutung: 'Sofort verständlich, überzeugend.', beispiel: 'Das ist ein einleuchtendes Argument.' },
      { wort: 'bedenklich', bedeutung: 'So, dass es Sorgen bereitet.', beispiel: 'Diese Entwicklung finde ich bedenklich.' },
      { wort: 'überzeugend', bedeutung: 'So, dass es andere wirklich überzeugt.', beispiel: 'Sie hat sehr überzeugend argumentiert.' },
      { wort: 'weitreichend', bedeutung: 'Mit großen, weit wirkenden Folgen.', beispiel: 'Die Entscheidung hat weitreichende Konsequenzen.' },
      { wort: 'stichhaltig', bedeutung: 'Logisch schlüssig, gut begründet.', beispiel: 'Dafür gibt es keine stichhaltigen Beweise.' },
      { wort: 'voreilig', bedeutung: 'Zu schnell, ohne genug nachzudenken.', beispiel: 'Zieh keine voreiligen Schlüsse.' },
      { wort: 'angebracht', bedeutung: 'Passend, in der Situation richtig.', beispiel: 'Ein bisschen Vorsicht wäre hier angebracht.' },
    ],
  },
  {
    id: 'nomen',
    titel: 'Wichtige Nomen',
    beschreibung: 'Abstrakte Hauptwörter, die in Diskussionen und Erklärungen immer wieder gebraucht werden.',
    eintraege: [
      { wort: 'der Aspekt', bedeutung: 'Ein bestimmter Gesichtspunkt einer Sache.', beispiel: 'Diesen Aspekt hatte ich noch gar nicht bedacht.' },
      { wort: 'die Voraussetzung', bedeutung: 'Etwas, das erfüllt sein muss, damit etwas anderes geht.', beispiel: 'Gegenseitiges Vertrauen ist die Voraussetzung dafür.' },
      { wort: 'die Auswirkung', bedeutung: 'Die Folge, die etwas nach sich zieht.', beispiel: 'Das hat spürbare Auswirkungen auf den Alltag.' },
      { wort: 'der Zusammenhang', bedeutung: 'Die Verbindung zwischen zwei Dingen.', beispiel: 'In diesem Zusammenhang ist das durchaus wichtig.' },
      { wort: 'das Ausmaß', bedeutung: 'Wie groß oder umfangreich etwas ist.', beispiel: 'Das Ausmaß des Problems wurde erst spät klar.' },
      { wort: 'die Herausforderung', bedeutung: 'Eine schwierige Aufgabe, die man meistern will.', beispiel: 'Das ist eine echte Herausforderung für uns alle.' },
      { wort: 'der Standpunkt', bedeutung: 'Die eigene Position, Sichtweise.', beispiel: 'Ich verstehe deinen Standpunkt, teile ihn aber nicht ganz.' },
      { wort: 'die Hinsicht', bedeutung: 'Ein Blickwinkel („in dieser Hinsicht“).', beispiel: 'In dieser Hinsicht gebe ich dir recht.' },
      { wort: 'der Anhaltspunkt', bedeutung: 'Ein Hinweis, an dem man sich orientieren kann.', beispiel: 'Dafür haben wir bisher keinen Anhaltspunkt.' },
      { wort: 'die Bandbreite', bedeutung: 'Die Spanne bzw. Vielfalt von etwas.', beispiel: 'Die Bandbreite an Meinungen ist enorm.' },
      { wort: 'der Kompromiss', bedeutung: 'Eine Lösung, bei der beide Seiten nachgeben.', beispiel: 'Am Ende fanden wir einen guten Kompromiss.' },
      { wort: 'die Ursache', bedeutung: 'Der Grund, warum etwas geschieht.', beispiel: 'Wir müssen zuerst die Ursache finden.' },
      { wort: 'der Vorbehalt', bedeutung: 'Ein Bedenken, eine Einschränkung.', beispiel: 'Ich stimme zu, allerdings mit einem Vorbehalt.' },
      { wort: 'die Tendenz', bedeutung: 'Eine Richtung, in die sich etwas entwickelt.', beispiel: 'Die Tendenz geht eindeutig nach oben.' },
      { wort: 'der Spielraum', bedeutung: 'Der Freiraum, den man für Entscheidungen hat.', beispiel: 'Beim Preis haben wir kaum Spielraum.' },
    ],
  },
  {
    id: 'konnektoren',
    titel: 'Konnektoren & Verbindungswörter',
    beschreibung: 'Wörter, die Gedanken logisch verknüpfen und deine Rede strukturiert wirken lassen.',
    eintraege: [
      { wort: 'dennoch', bedeutung: 'Trotzdem (gehobener). Am Satzanfang folgt sofort das Verb.', beispiel: 'Es war riskant; dennoch hat es sich gelohnt.' },
      { wort: 'folglich', bedeutung: 'Als logische Konsequenz, also deshalb.', beispiel: 'Die Nachfrage sank; folglich mussten wir umplanen.' },
      { wort: 'zumal', bedeutung: 'Weil ja außerdem – setzt einen verstärkenden Grund drauf.', beispiel: 'Wir sollten zusagen, zumal sich das selten bietet.' },
      { wort: 'indem', bedeutung: 'Beschreibt, wie/womit man etwas erreicht.', beispiel: 'Er überzeugte, indem er ruhig blieb.' },
      { wort: 'hingegen', bedeutung: 'Im Gegensatz dazu.', beispiel: 'Ich mag Tee; Kaffee hingegen trinke ich selten.' },
      { wort: 'gleichwohl', bedeutung: 'Trotzdem (sehr gehoben).', beispiel: 'Der Weg ist teuer; gleichwohl ist er richtig.' },
      { wort: 'insofern', bedeutung: 'In dieser Beziehung / deshalb in gewissem Sinne.', beispiel: 'Insofern hast du völlig recht.' },
      { wort: 'wobei', bedeutung: 'Hängt eine Einschränkung oder Bemerkung an.', beispiel: 'Der Plan ist gut, wobei die Kosten offen sind.' },
      { wort: 'demzufolge', bedeutung: 'Dem zufolge, also als Schlussfolgerung.', beispiel: 'Die Zahlen steigen; demzufolge läuft es gut.' },
      { wort: 'nichtsdestotrotz', bedeutung: 'Trotz allem, dennoch (betont).', beispiel: 'Es war anstrengend, nichtsdestotrotz hat es Spaß gemacht.' },
      { wort: 'einerseits … andererseits', bedeutung: 'Stellt zwei Seiten gegenüber.', beispiel: 'Einerseits reizt es mich, andererseits fehlt die Zeit.' },
      { wort: 'zwar … aber', bedeutung: 'Räumt etwas ein und schränkt es dann ein.', beispiel: 'Das ist zwar teuer, aber es hält ewig.' },
      { wort: 'je … desto', bedeutung: 'Zwei Dinge steigen gemeinsam.', beispiel: 'Je mehr man übt, desto sicherer wird man.' },
      { wort: 'darüber hinaus', bedeutung: 'Zusätzlich, außerdem (gehoben).', beispiel: 'Darüber hinaus spart es auch noch Zeit.' },
      { wort: 'letztlich', bedeutung: 'Am Ende, wenn man alles betrachtet.', beispiel: 'Letztlich kommt es auf die Umsetzung an.' },
    ],
  },
  {
    id: 'meinung',
    titel: 'Redemittel: Meinung & Argumentation',
    beschreibung: 'Feste Wendungen, um souverän eine Meinung zu äußern, zuzustimmen oder zu widersprechen.',
    eintraege: [
      { wort: 'Ich bin der Ansicht, dass …', bedeutung: 'Meine Meinung ausdrücken (gehoben).', beispiel: 'Ich bin der Ansicht, dass wir mehr Zeit brauchen.' },
      { wort: 'Meiner Einschätzung nach …', bedeutung: 'So beurteile ich die Lage.', beispiel: 'Meiner Einschätzung nach ist das zu optimistisch.' },
      { wort: 'Da bin ich ganz deiner Meinung.', bedeutung: 'Volle Zustimmung.', beispiel: 'Da bin ich ganz deiner Meinung, so sehe ich das auch.' },
      { wort: 'Das sehe ich anders.', bedeutung: 'Höflicher Widerspruch.', beispiel: 'Das sehe ich ehrlich gesagt etwas anders.' },
      { wort: 'Da muss ich widersprechen.', bedeutung: 'Klarer, aber sachlicher Widerspruch.', beispiel: 'Da muss ich dir leider widersprechen.' },
      { wort: 'Es lässt sich nicht leugnen, dass …', bedeutung: 'Etwas Offensichtliches einräumen.', beispiel: 'Es lässt sich nicht leugnen, dass es teurer wird.' },
      { wort: 'Ich würde behaupten, dass …', bedeutung: 'Eine Meinung etwas vorsichtiger setzen.', beispiel: 'Ich würde behaupten, dass das die bessere Lösung ist.' },
      { wort: 'Da ist etwas dran.', bedeutung: 'Teilweise zustimmen.', beispiel: 'Da ist durchaus etwas dran, aber …' },
      { wort: 'Das kann man so nicht sagen.', bedeutung: 'Eine Pauschalaussage zurückweisen.', beispiel: 'Das kann man so pauschal nicht sagen.' },
      { wort: 'im Großen und Ganzen', bedeutung: 'Insgesamt betrachtet.', beispiel: 'Im Großen und Ganzen bin ich zufrieden.' },
      { wort: 'Ich gebe zu bedenken, dass …', bedeutung: 'Höflich einen Einwand einbringen.', beispiel: 'Ich gebe zu bedenken, dass die Zeit knapp ist.' },
      { wort: 'Genau das ist der Punkt.', bedeutung: 'Etwas als Kern der Sache bestätigen.', beispiel: 'Genau das ist der Punkt, den ich meine.' },
      { wort: 'unterm Strich', bedeutung: 'Am Ende, alles zusammengerechnet.', beispiel: 'Unterm Strich hat sich der Aufwand gelohnt.' },
      { wort: 'Ich bin hin- und hergerissen.', bedeutung: 'Ich kann mich nicht entscheiden.', beispiel: 'Ehrlich gesagt bin ich da hin- und hergerissen.' },
    ],
  },
  {
    id: 'diskussion',
    titel: 'Redemittel: Diskussion steuern',
    beschreibung: 'Wendungen, um sich einzubringen, nachzufragen und ein Gespräch elegant zu lenken.',
    eintraege: [
      { wort: 'Darf ich kurz einhaken?', bedeutung: 'Höflich unterbrechen, um etwas zu sagen.', beispiel: 'Darf ich hier kurz einhaken?' },
      { wort: 'Um noch einmal auf … zurückzukommen', bedeutung: 'Zu einem früheren Punkt zurückkehren.', beispiel: 'Um noch einmal auf die Kosten zurückzukommen …' },
      { wort: 'Wenn ich dich richtig verstehe, …', bedeutung: 'Das Gesagte absichern und zusammenfassen.', beispiel: 'Wenn ich dich richtig verstehe, willst du mehr Zeit.' },
      { wort: 'Lass mich kurz ausreden.', bedeutung: 'Freundlich darum bitten, weitersprechen zu dürfen.', beispiel: 'Lass mich das bitte kurz zu Ende bringen.' },
      { wort: 'Das führt zu weit.', bedeutung: 'Signalisieren, dass man vom Thema abkommt.', beispiel: 'Das führt jetzt zu weit, das klären wir später.' },
      { wort: 'Kommen wir zum Punkt.', bedeutung: 'Zum Wesentlichen zurückkehren.', beispiel: 'Kommen wir zum eigentlichen Punkt.' },
      { wort: 'Wie meinst du das genau?', bedeutung: 'Um eine Präzisierung bitten.', beispiel: 'Wie meinst du das genau? Kannst du das ausführen?' },
      { wort: 'Das würde ich gern vertiefen.', bedeutung: 'Ein Thema genauer besprechen wollen.', beispiel: 'Diesen Gedanken würde ich gern vertiefen.' },
      { wort: 'Bleiben wir mal sachlich.', bedeutung: 'Zu einer ruhigen Ebene zurückführen.', beispiel: 'Bleiben wir bitte sachlich.' },
      { wort: 'Fassen wir zusammen: …', bedeutung: 'Das Wichtigste bündeln.', beispiel: 'Fassen wir zusammen: Wir sind uns weitgehend einig.' },
      { wort: 'Ich schließe mich dem an.', bedeutung: 'Der Meinung eines anderen zustimmen.', beispiel: 'Ich schließe mich meinem Vorredner an.' },
      { wort: 'Nur der Vollständigkeit halber …', bedeutung: 'Etwas ergänzen, damit nichts fehlt.', beispiel: 'Nur der Vollständigkeit halber sei erwähnt, dass …' },
    ],
  },
  {
    id: 'alltag',
    titel: 'Redemittel: Gespräch & Alltag',
    beschreibung: 'Lockere, natürliche Wendungen für ungezwungene Gespräche — damit du nicht nur formell klingst.',
    eintraege: [
      { wort: 'Kommt drauf an.', bedeutung: 'Die Antwort hängt von den Umständen ab.', beispiel: '„Gehst du mit?“ – „Kommt drauf an, wann.“' },
      { wort: 'Mach dir keinen Kopf.', bedeutung: 'Mach dir keine Sorgen (locker).', beispiel: 'Mach dir keinen Kopf, das wird schon.' },
      { wort: 'Das passt mir gut.', bedeutung: 'Das kommt mir gelegen.', beispiel: 'Freitag? Ja, das passt mir gut.' },
      { wort: 'Ich bin gespannt.', bedeutung: 'Ich bin neugierig, wie es wird.', beispiel: 'Ich bin gespannt, was dabei rauskommt.' },
      { wort: 'Na ja, es geht so.', bedeutung: 'Weder gut noch schlecht.', beispiel: '„Wie läuft’s?“ – „Na ja, es geht so.“' },
      { wort: 'Das ist mir egal.', bedeutung: 'Ich habe keine Präferenz.', beispiel: 'Wo wir essen, ist mir ehrlich gesagt egal.' },
      { wort: 'Ehrlich gesagt …', bedeutung: 'Leitet eine offene, ehrliche Aussage ein.', beispiel: 'Ehrlich gesagt hatte ich keine Lust.' },
      { wort: 'Das kann ich mir gut vorstellen.', bedeutung: 'Das leuchtet mir ein / das finde ich denkbar.', beispiel: 'Dass er müde war, kann ich mir gut vorstellen.' },
      { wort: 'Da hast du recht.', bedeutung: 'Zustimmung im Alltag.', beispiel: 'Stimmt, da hast du völlig recht.' },
      { wort: 'Lass uns das später klären.', bedeutung: 'Etwas auf später verschieben.', beispiel: 'Lass uns das in Ruhe später klären.' },
      { wort: 'Ich meld mich.', bedeutung: 'Ich gebe später Bescheid (locker).', beispiel: 'Alles klar, ich meld mich bei dir.' },
      { wort: 'Kein Ding.', bedeutung: 'Kein Problem (umgangssprachlich).', beispiel: '„Danke dir!“ – „Kein Ding.“' },
      { wort: 'Das liegt mir auf der Zunge.', bedeutung: 'Ich weiß es fast, komme aber nicht drauf.', beispiel: 'Wie hieß der Film noch … das liegt mir auf der Zunge.' },
      { wort: 'Mal sehen.', bedeutung: 'Ich entscheide später / abwarten.', beispiel: '„Kommst du?“ – „Mal sehen.“' },
    ],
  },
  {
    id: 'idiome',
    titel: 'Idiomatische Ausdrücke',
    beschreibung: 'Feste Redewendungen, die deine Sprache lebendig und muttersprachlich klingen lassen — sparsam einsetzen.',
    eintraege: [
      { wort: 'den Nagel auf den Kopf treffen', bedeutung: 'Etwas genau richtig auf den Punkt bringen.', beispiel: 'Mit der Bemerkung hast du den Nagel auf den Kopf getroffen.' },
      { wort: 'auf dem Schlauch stehen', bedeutung: 'Gerade nicht draufkommen, blockiert sein.', beispiel: 'Sorry, ich steh gerade total auf dem Schlauch.' },
      { wort: 'aus dem Bauch heraus', bedeutung: 'Spontan, nach Gefühl entscheiden.', beispiel: 'Ich habe das aus dem Bauch heraus entschieden.' },
      { wort: 'die Daumen drücken', bedeutung: 'Jemandem Glück wünschen.', beispiel: 'Ich drücke dir für morgen die Daumen!' },
      { wort: 'ins kalte Wasser springen', bedeutung: 'Etwas Neues ohne Vorbereitung wagen.', beispiel: 'Beim neuen Job musste ich ins kalte Wasser springen.' },
      { wort: 'unter einen Hut bringen', bedeutung: 'Verschiedene Dinge miteinander vereinbaren.', beispiel: 'Familie und Beruf unter einen Hut zu bringen, ist schwer.' },
      { wort: 'die Katze aus dem Sack lassen', bedeutung: 'Ein Geheimnis endlich verraten.', beispiel: 'Jetzt lass endlich die Katze aus dem Sack!' },
      { wort: 'Tacheles reden', bedeutung: 'Offen und deutlich die Wahrheit sagen.', beispiel: 'Wir müssen mal Tacheles reden.' },
      { wort: 'jemandem auf die Nerven gehen', bedeutung: 'Jemanden nerven.', beispiel: 'Der Lärm geht mir echt auf die Nerven.' },
      { wort: 'ein Auge zudrücken', bedeutung: 'Etwas nachsichtig durchgehen lassen.', beispiel: 'Diesmal drücke ich noch ein Auge zu.' },
      { wort: 'die Nase voll haben', bedeutung: 'Genug von etwas haben.', beispiel: 'Ich habe langsam die Nase voll von der Warterei.' },
      { wort: 'auf Nummer sicher gehen', bedeutung: 'Kein Risiko eingehen.', beispiel: 'Ich gehe lieber auf Nummer sicher und frage nach.' },
      { wort: 'Bahnhof verstehen', bedeutung: 'Gar nichts verstehen.', beispiel: 'Bei dem Vortrag habe ich nur Bahnhof verstanden.' },
      { wort: 'jemandem reinen Wein einschenken', bedeutung: 'Jemandem die unangenehme Wahrheit sagen.', beispiel: 'Ich sollte ihr endlich reinen Wein einschenken.' },
      { wort: 'das A und O', bedeutung: 'Das Wichtigste an einer Sache.', beispiel: 'Gute Vorbereitung ist das A und O.' },
    ],
  },
]

export const gesamtzahlVokabeln = vokabular.reduce((s, g) => s + g.eintraege.length, 0)
